[package]
name = "imgfind"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true

[profile.dev.package.image]
opt-level = 3

[dependencies]
clipper = { version = "0.1.0", path = "../clipper" }
oshash = "0.2.0"
clap = { version = "4.0", features = ["derive"] }
diesel = { version = "2.0", features = [
    "sqlite",
    "returning_clauses_for_sqlite_3_35",
] }
diesel_migrations = "2.0"
rusqlite = { version = "0.37", features = ["bundled"] }
sqlite-vec = "0.1"
zerocopy = "0.8"
walkdir = "2.0"
image = "0.25"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
regex = "1.10"
dirs = "5.0"
tokio = { version = "1.0", features = ["full", "rt-multi-thread", "tracing"] }
log = "0.4"
indicatif = "0.17"
tracing-subscriber = "0.3.19"
axum = { version = "0.8.4", features = ["http2", "macros"] }
juniper = { version = "0.16.1", features = ["anyhow"] }
juniper_axum = "0.2.0"
serde_json = "1.0.140"
tower-http = { version = "0.6.6", features = [
    "compression-gzip",
    "compression-zstd",
    "compression-deflate",
    "full",
] }
tower = { version = "0.5.2", features = ["full", "tokio"] }
tracing = "0.1.41"
axum-extra = "0.10.1"
rust-embed = "8.7.2"
mime_guess = "2.0.5"
rayon = "1.10.0"
iterm2img = "0.1.0"
r2d2_sqlite = { version = "0.31.0", features = ["bundled"] }
r2d2 = "0.8.10"
base64 = "0.22.1"
